### ISSUE TITLE
H_T_Prime in non-N-body Gauge

### ISSUE THREAD

**Issue by joshwfoster** [jmd-dk/Nbody#10]
The lines 480-481 in the linear.py module force the `H_T_prime` perturbation to be present in the class output for all gauges. 

I believe the `H_T_prime` perturbation is only used in the n-body gauge and so needs not be included for synchronous or Newtonian gauge simulations?

**Comment by jmd-dk** [comment]
You are right, the reason for including `H_T_prime` as a needed perturbation at these specific lines of code is due to a velocity variable transformation. Though not a gauge transformation, I think this transformation only makes sense in the *N*-body gauge.

However, at this point in the code, it is not obvious what gauge is to be imposed. The code does not enforce a global gauge for all perturbations (though probably this is always what one wants). So placing something like `if gauge == nbody` here is not easy.

Do you run into trouble because of this? Or maybe this "just" triggers a rerunning of CLASS for every simulation?
Can you share a parameter file for which the trouble occurs, assuming it works with the unmodified CO*N*CEPT source code?

**Comment by joshwfoster** [comment]
No problems with the unmodified source code. It triggered some errors in my modified version, and I thought I would just point it out because having transfer functions present for a gauge that is different than the run-time gauge seems like a way issues might creep in in the future. Thanks!
