### ISSUE TITLE
Sometimes the long-range evaluation takes a long time

### ISSUE THREAD

**Issue by andrea-begnoni** [jmd-dk/Nbody#14]
Hi,

this could be an issue with the cluster I am using but I'd like to hear an opinion.

Sometimes the long-range evaluation for a single step of large simulations takes $\approx 20$ min while it should take $< 2$ min. This repeats for all the steps of the simulation and it is not related to the specific jobs.

Here are some of the parameters of the simulation:
- particle number: 4096^3
- number of cpus: 4096
- number of nodes: 64
- number of tasks-per-node: 64
- number of cpus-per-task: 1
- $L_{box}$= 2625 Mpc/h (but this happened also for other resolutions)

The batch script is a modified version of the one **concept** generates automatically, where I request 64 nodes. Moreover, for each node I ask for 64 tasks (I found this to be significantly faster than asking for 1 tasks-per-node and 64 cpus-per-task).

Here I attach the preview of two log files. They represent the same parameter file, the simulation starts at $a=0.7$ and starts from a previous snapshot ran with **concept**. 

This is the one that takes a long time
![Pasted image 20241203164040](https://github.com/user-attachments/assets/01e33487-0200-4da3-b813-6c9e3c8bb092)

This is the one I re-run after stopping the first one
![Pasted image 20241203163959](https://github.com/user-attachments/assets/799611c8-47d9-44e6-a090-e0d6fc9b0985)

What could be the origin of this issue? It did not occur for smaller simulations (I tested up to $N=2000^3$).
At the moment it seems to happen quite often: of the last 8 jobs it happened 7 times. 

It happens in a wide range of situations: starting from snapshots, starting from autosaved snapshots. Once it also happened at the creation of ICs, where the creation took a factor $\times 10-15$ more than previously found. 

Thanks for any possible explanation or insights.

**Comment by jmd-dk** [comment]
I guess there could be several possible explanations for this, but one that immediately comes to mind is bad network connection for one or more of the nodes on your cluster. The long-range force (FFT) requires a lot communication between processes, so if a particular node is slow in this regard for whatever reason, it can slow down this computation a lot. By checking the list of compute nodes assigned to your job, you can see if this is the case. If two jobs with identically assigned node lists yield both a slow and a fast long-range computation, this is *not* the reason for it.

I have had a similar issue in the past and managed to wiggle it down to a particular, bad node. If I was unlucky and my job got assigned this node, I would submit the same job again, hoping that it would run immediately (and thus be guaranteed to *not* get assigned the bad, now occupied node), then kill the first job. :upside_down_face: 

I see that in both of your logs, the FFTW wisdom is regenerated. I doubt this is the cause of trouble, but in principle it could be that sometimes it generates some bad wisdom, leading to slow computations. By using the following parameters, the wisdom generated for a given problem (grid size) will be reused across different sets of nodes (and thus simulations):
```
fftw_wisdom_reuse = True
fftw_wisdom_share = True
```
So if you add this to your parameter file and launch a job where the long-range computation is fast, the next job should fetch the cached wisdom from disk instead of regenerating it. Conversely, if some "bad wisdom" is generated, all future jobs should then also be slow. You can clear the wisdom cache by
```
(source concept && make clean-fftw-reusable)
```

**Comment by jmd-dk** [comment]
Aside on viewing of log files: Try
```
less -rf job/<jobid>/log
```
then the formatting is displayed correctly.

**Comment by andrea-begnoni** [comment]
Thank you very much for the detailed and fast reply. I'll try your suggestions soon :smile: 
I close the issue now.
