### ISSUE TITLE
invalid syntax of render2D

### ISSUE THREAD

**Issue by wuchenglon** [jmd-dk/Nbody#8]
I made a param file and ran it with concept but it returns me a  invalid syntax of render2D like follow:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/user/test/disk/concept/dep/python/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 8
    'render2D': a_begin
    ^
SyntaxError: invalid syntax
An error occurred!
I learned the tutorial and tired to modify the code but still can't work,and here's my code:
initial_conditions = {
    'species': 'matter',
    'N'      : 64**3,
}

output_times = {
'snapshot': a_begin
'render2D': a_begin
}
output_dirs = {
'snapshot': path.output_dir
'render2D': path.output_dir
}

render2D_select = {
    'all': {
        'data'          : False,
        'image'         : True,
        'terminal image': True,
    },
}

snapshot_select = {
    'save': {
        'matter': {
            'pos': True,
            'mom': True,
            'J'  : True,
        },
    },
    'load': {
        'matter': {
            'pos': True,
            'mom': True,
            'J'  : True,
        },
    },
}
snapshot_type = 'concept'

boxsize = 256*Mpc/h
potential_options = 128 

H0 = 67*km/(s*Mpc)
Ωb = 0.049
Ωcdm = 0.27
a_begin = 0.02
primordial_spectrum = {
    'A_s': 2.1e-9,  # Amplitude
    'n_s': 0.96,    # Tilt / spectral index
}

**Comment by jmd-dk** [comment]
Hello @wuchenglon. The different items within Python dictionaries need to be separated by commas (`,`). You currently have this:
```python3
output_times = {
    'snapshot': a_begin
    'render2D': a_begin
}
```
but need to add a comma like so:
```python3
output_times = {
    'snapshot': a_begin,
    'render2D': a_begin
}
```
(you even see that the syntax highlighting here on GitHub is not happy about the first case).
Since Python allows trailing commas, I recommend adding one more comma:
```python3
output_times = {
    'snapshot': a_begin,
    'render2D': a_begin,
}
```
(this way, you won't forget the comma if you one day add another item/line).

Note that the above is purely about Python syntax, it is not specific to CO*N*CEPT. You have the same issue for `output_dirs`.

A separate issue is your way of defining `H0`:
```python3
H0 = 67km/(sMpc)
```
You need to write this as
```python3
H0 = 67*km/(s*Mpc)
```
as 1) Python does not understand things like `67km` and 2) CO*N*CEPT only defines individual "basic" units, like `s` and `Mpc`, not products like `sMpc = s*Mpc`.

May I ask whether you've written these parameter definitions out yourself, or have you obtained them from copying code from somewhere (e.g. the [documentation](https://jmd-dk.github.io/concept/))?

**Comment by wuchenglon** [comment]
> Hello @wuchenglon. The different items within Python dictionaries need to be separated by commas (). You currently have this:`,`
> 
> ```python
> output_times = {
>     'snapshot': a_begin
>     'render2D': a_begin
> }
> ```
> 
> but need to add a comma like so:
> 
> ```python
> output_times = {
>     'snapshot': a_begin,
>     'render2D': a_begin
> }
> ```
> 
> (you even see that the syntax highlighting here on GitHub is not happy about the first case). Since Python allows trailing commas, I recommend adding one more comma:
> 
> ```python
> output_times = {
>     'snapshot': a_begin,
>     'render2D': a_begin,
> }
> ```
> 
> (this way, you won't forget the comma if you one day add another item/line).
> 
> Note that the above is purely about Python syntax, it is not specific to CO_N_CEPT. You have the same issue for .`output_dirs`
> 
> A separate issue is your way of defining :`H0`
> 
> ```python
> H0 = 67km/(sMpc)
> ```
> 
> You need to write this as
> 
> ```python
> H0 = 67*km/(s*Mpc)
> ```
> 
> as 1) Python does not understand things like and 2) CO_N_CEPT only defines individual "basic" units, like and , not products like .`67km``s``Mpc``sMpc = s*Mpc`
> 
> May I ask whether you've written these parameter definitions out yourself, or have you obtained them from copying code from somewhere (e.g. the [documentation](https://jmd-dk.github.io/concept/))?

Hi jmd-dk, thank you for your careful guidance. Indeed I learned and copied code from https://jmd-dk.github.io/concept/ and example_basic from concept/param and it's my fault that lack of inspection, now I get the file what I want.
Thanks again for your generous help.
